1112466_1112492/Controllers/DangKyController.cs
using _1112466_1112492.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _1112466_1112492.Controllers
{
    public class DangKyController : Controller
    {
        QLMonAn.QuanLyMonAnEntities db = new QLMonAn.QuanLyMonAnEntities();
        //
        // GET: /DangKy/
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult KetQuaDangKy(DangKyModels model)
        {
            //ViewBag.Message = "Dang ky thanh cong";
            ViewBag.TenDangNhap = model.TenTaiKhoan;

            ViewBag.MatKhau = model.MatKhau;

            ViewBag.NhapLaiMatKhau = model.NhapLaiMatKhau;
            
            ViewBag.Email = model.Email;

            if (Request["cbGioiTinh"] == "nam")
                ViewBag.GioiTinh = "Nam";
            else if (Request["cbGioiTinh"] == "nu")
                ViewBag.GioiTinh = "Nữ";

            ViewBag.NgaySinh = Request["datepicker"];

            if (Request["cbNoiO"] == "hcm")
                ViewBag.NoiO = "Hồ Chí Minh";
            else if (Request["cbNoiO"] == "hn")
                ViewBag.NoiO = "Hà Nội";
            else if (Request["cbNoiO"] == "hue")
                ViewBag.NoiO = "Huế";

            ViewBag.DienThoai = model.DienThoai;
            return View();
        }

        [HttpPost]
        public ActionResult KetQuaTaoMonAn(MonAnModel model)
        {
            QLMonAn.MonAn ma = new QLMonAn.MonAn();
            try
            {
                ma.TenMonAn = model.TenMonAn;
                ma.DonGia = Int32.Parse(model.DonGia);
                ma.MoTa = model.MoTa;
                if (Request["cbLoaiMonAn"] == "heo")
                {
                    ma.LoaiMonAn = 1;
                }
                else if (Request["cbLoaiMonAn"] == "bo")
                    ma.LoaiMonAn = 2;
                else if (Request["cbLoaiMonAn"] == "ga")
                    ma.LoaiMonAn = 3;
                else if (Request["cbLoaiMonAn"] == "haisan")
                    ma.LoaiMonAn = 4;

                if (Request["tinhtrang"] == "ss")
                    ma.TinhTrang = true;
                else
                    ma.TinhTrang = false;

                if (Request["odau"] == "bac")
                    ma.XuatXu = "Miền Bắc";
                else if (Request["odau"] == "trung")
                    ma.XuatXu = "Miền Trung";
                else if (Request["odau"] == "nam")
                    ma.XuatXu = "Miền Nam";
                else if (Request["odau"] == "tay")
                    ma.XuatXu = "Miền Tây";

                db.MonAns.Add(ma);
                db.SaveChanges();

                int id = ma.MaMonAn;

                QLMonAn.HinhAnh ha = new QLMonAn.HinhAnh();
                ha.MaMonAn = id;
                ha.LinkHinhAnh = model.linkhinhanh1;
                db.HinhAnhs.Add(ha);
                db.SaveChanges();

                if (model.linkhinhanh2 != null)
                {
                    ha.MaMonAn = id;
                    ha.LinkHinhAnh = model.linkhinhanh2;
                    db.HinhAnhs.Add(ha);
                    db.SaveChanges();
                }

                if (model.linkhinhanh3 != null)
                {
                    ha.MaMonAn = id;
                    ha.LinkHinhAnh = model.linkhinhanh3;
                    db.HinhAnhs.Add(ha);
                    db.SaveChanges();
                }
            }
            catch (DbEntityValidationException ex)
            {
                
            }
            

            
            return RedirectToAction("Index", "MonAn");
        }
	}
}

1112466_1112492/Controllers/MonAnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLMonAn;
using System.Net;
using PagedList;
using System.Data.Entity;
using System.Data.Entity.Validation;
using Microsoft.AspNet.Identity;
namespace _1112466_1112492.Controllers
{
    public class MonAnController : Controller
    {
        private QuanLyMonAnEntities db = new QuanLyMonAnEntities();
        private DBHelper dbhelper = new DBHelper();
        private List<MonAn> kqMonAn = new List<MonAn>();

        //
        // GET: /MonAn/
        public ActionResult Index(int? page, string UserName)
        {
            ViewBag.UserName = UserName;
            
            int pageSize = 3;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            List<HinhAnh> hinhanh = dbhelper.GetHinhAnhs(); //((from ha in db.HinhAnhs
                                     // select ha)).ToList();

            IPagedList<MonAn> monan = //(from ma in db.MonAns
                                       //select ma).OrderByDescending(m => m.TenMonAn)
                                    dbhelper.GetMonAnsDesByName().ToPagedList(pageIndex, pageSize);
            for (int i = 0; i < hinhanh.Count; i++)
            {
                for (int j = 0; j < monan.Count; j++)
                    if (monan[j].MaMonAn == hinhanh[i].MaMonAn)
                        monan[j].LinkHinhAnh.Add(hinhanh[i].LinkHinhAnh);
            }
            
            return View(monan);
           
        }

        //
        // GET: /About/
        public ActionResult About(string UserName)
        {
            ViewBag.UserName = UserName;
            return View();
        }

        //
        // GET: /ListTheoAnGi/
        public ActionResult ListTheoAnGi(string loaimonan, int? page, string UserName)
        {
            ViewBag.UserName = UserName;
            ViewBag.loaimonan = new SelectList(dbhelper.GetLoaiMonAn(), "MaLoaiMonAn", "TenLoai");//.LoaiMonAns.ToList()
            int pageSize = 3;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            List<HinhAnh> hinhanh = dbhelper.GetHinhAnhs(); // ((from ha in db.HinhAnhs
                                      //select ha)).ToList();

            ViewBag.Loai = "tất cả";
            IPagedList<MonAn> monan = //(from ma in db.MonAns
                                       //select ma).OrderByDescending(m => m.TenMonAn)
                                        dbhelper.GetMonAnsDesByName().ToPagedList(pageIndex, pageSize);
            if (!string.IsNullOrWhiteSpace(loaimonan))
            
            {
                int id = Int32.Parse(loaimonan);
                List<LoaiMonAn> lman = dbhelper.GetLoaiMonAnById(id); //(from lma in db.LoaiMonAns
                                 //where lma.MaLoaiMonAn == id
                                 //select lma).ToList();
                ViewBag.Loai = "món " + lman[0].TenLoai;
                monan = //(from ma in db.MonAns
                          //   select ma).Where(ma => ma.LoaiMonAn == id).OrderByDescending(m => m.TenMonAn)
                        dbhelper.GetMonAnsDesByNameAndId(id).ToPagedList(pageIndex, pageSize);
            }

            for (int i = 0; i < hinhanh.Count; i++)
            {
                for (int j = 0; j < monan.Count; j++)
                    if (monan[j].MaMonAn == hinhanh[i].MaMonAn)
                        monan[j].LinkHinhAnh.Add(hinhanh[i].LinkHinhAnh);
            }
            return View(monan);
        }

        //
        // GET: /ListTheoODau/
        public ActionResult ListTheoODau(string odau, int? page, string UserName)
        {
            ViewBag.UserName = UserName;
            int pageSize = 3;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            List<HinhAnh> hinhanh = dbhelper.GetHinhAnhs();//((from ha in db.HinhAnhs
                                      //select ha)).ToList();

            IPagedList<MonAn> listmonan;
            if (string.IsNullOrWhiteSpace(odau))
            {
                ViewBag.Loai = "tất cả";
                listmonan = //(from ma in db.MonAns
                             //select ma).OrderByDescending(m => m.TenMonAn)
                            dbhelper.GetMonAnsDesByName().ToPagedList(pageIndex, pageSize);
            }
            else
            {
                string xuatxu = "";
                if (odau == "bac") xuatxu = "Miền Bắc";
                else if (odau == "trung") xuatxu = "Miền Trung";
                else if (odau == "nam") xuatxu = "Miền Nam";
                else if (odau == "tay") xuatxu = "Miền Tây";
                listmonan = //(from ma in db.MonAns
                            // select ma).Where(ma => ma.XuatXu == xuatxu).OrderByDescending(m => m.TenMonAn)
                            dbhelper.GetMonAnsDesByNameAndXuatxu(xuatxu).ToPagedList(pageIndex, pageSize);
            }

            for (int i = 0; i < hinhanh.Count; i++)
            {
                for (int j = 0; j < listmonan.Count; j++)
                    if (listmonan[j].MaMonAn == hinhanh[i].MaMonAn)
                        listmonan[j].LinkHinhAnh.Add(hinhanh[i].LinkHinhAnh);
            }
            return View(listmonan);
        }

        //
        // GET: /ListTheoSignUp/
        public ActionResult SignUp()
        {
            return View();
        }

        //
        // GET: /ChiTietMonAn/
        public ActionResult ChiTietMonAn(int? id, string UserName)
        {
            ViewBag.UserName = UserName;
            //ViewBag.MaMonAn = id;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int idmonan = (int)id;
            MonAn ma = dbhelper.GetMonAnById(idmonan);//db.MonAns.Find(id);
            List<HinhAnh> hinhanh = dbhelper.GetHinhAnhsById(idmonan);//(from ha in db.HinhAnhs
                                     //where ha.MaMonAn == id
                                     //select ha).ToList();
            List<Comment> dsBinhLuan = dbhelper.GetCommentById(idmonan);//(from bl in db.Comments
                                        //where bl.MaMonAn == id
                                        //select bl).ToList();
            for (int i = dsBinhLuan.Count - 1; i >= 0; i--)
            {
                ma.listBinhLuan.Add(dsBinhLuan[i]);
            }
            for (int i = 0; i < hinhanh.Count; i++)
                ma.LinkHinhAnh.Add(hinhanh[i].LinkHinhAnh);
            if (ma == null)
            {
                return HttpNotFound();
            }
           
            return View(ma);
        }
        [HttpGet]
        public ActionResult GioHang(string UserName)
        {
            ViewBag.UserName = UserName;
            var kq = dbhelper.GetGioHang();//(from gh in db.GioHangTamThois
                     //select gh).ToList();
            var tongtien = kq.Select(m => m.Gia).Sum();
            ViewBag.TongTien = tongtien;
            return View(kq);
        }
        [HttpGet]
        //
        // GET: /TimKiem/
        public ActionResult TimKiem(String pTenMonAn, int? page, string UserName)
        {
            ViewBag.UserName = UserName;
            if (pTenMonAn == null)
                return RedirectToAction("Index", "MonAn");
            int pageSize = 3;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            List<HinhAnh> hinhanh = dbhelper.GetHinhAnhs();//((from ha in db.HinhAnhs
                                     // select ha)).ToList();

            IPagedList<MonAn> monan = //(from ma in db.MonAns
                                       //select ma).Where(ma => ma.TenMonAn.Contains(pTenMonAn)).OrderByDescending(m => m.TenMonAn)
                                    dbhelper.GetMonAnsContainName(pTenMonAn).ToPagedList(pageIndex, pageSize);
            for (int i = 0; i < hinhanh.Count; i++)
            {
                for (int j = 0; j < monan.Count; j++)
                    if (monan[j].MaMonAn == hinhanh[i].MaMonAn)
                        monan[j].LinkHinhAnh.Add(hinhanh[i].LinkHinhAnh);
            }
            return View(monan);
            
        }

        
        [HttpGet]
        public ActionResult TimKiemNangCao(String XuatXu, String LoaiMonAn, String name_search, int? page, string UserName)
        {
            ViewBag.UserName = UserName;
            ViewBag.LoaiMonAn = Request["cbLoaiMonAn"] == null ? LoaiMonAn : Request["cbLoaiMonAn"];
            ViewBag.XuatXu = Request["odau"] == null ? XuatXu : Request["odau"];
            int pageSize = 3;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            List<HinhAnh> hinhanh = dbhelper.GetHinhAnhs(); //((from ha in db.HinhAnhs
                                     // select ha)).ToList();
            var _ma = dbhelper.GetMonAn();//from ma in db.MonAns
                     //select ma;
            if (name_search != null)
                _ma = _ma.Where(ma => ma.TenMonAn.Contains(name_search));
            if (Request["cbLoaiMonAn"] == "heo" || LoaiMonAn == "heo")
                _ma = _ma.Where(ma => ma.LoaiMonAn == 1);
            if (Request["cbLoaiMonAn"] == "bo" || LoaiMonAn == "bo")
                _ma = _ma.Where(ma => ma.LoaiMonAn == 2);
            if (Request["cbLoaiMonAn"] == "ga" || LoaiMonAn == "ga")
                _ma = _ma.Where(ma => ma.LoaiMonAn == 3);
            if (Request["cbLoaiMonAn"] == "haisan" || LoaiMonAn == "haisan")
                _ma = _ma.Where(ma => ma.LoaiMonAn == 4);
            if (Request["odau"] == "bac" || XuatXu == "bac")
                _ma = _ma.Where(ma => ma.XuatXu == "Miền Bắc");
            if (Request["odau"] == "trung" || XuatXu == "trung")
                _ma = _ma.Where(ma => ma.XuatXu == "Miền Trung");

1112466_1112492/Views/MonAn/SignUp.cshtml
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "SignUp";
}
@model _1112466_1112492.Models.DangKyModels


<div class="container">
    <div class="row" id="main_header">
        <div class="col-xs-4" id="logo_header">
            @Html.Label("EatEat", new { id = "textlarge_logo" })
            @Html.Label("Everywhere", new { id = "textsmall_logo" })
        </div>
        <div class="col-xs-4" id="search_box">
            @using (Html.BeginForm("TimKiem", "MonAn", FormMethod.Get))
            {
                <input name="pTenMonAn" id="search_box_input" type="text" placeholder="Type here">
                <input class="btnSearch" id="search_box_submit" type="submit" value="Search">
            }

        </div>
        <div class="col-xs-4" id="login_signup">
           @if (User.Identity.GetUserName() == "")
{
    @Html.ActionLink("SignUp", "Register", "Account", null, new { id = "signup" })
    @Html.Label("|", new { id = "temp1" })
    @Html.ActionLink("Login", "Login", "Account", null, new { id = "login" })
    @Html.Label("|", new { id = "temp1" })
    @Html.ActionLink("Cart", "Giohang", "MonAn", null, new { id = "signup" })
}
else
{

    @Html.ActionLink("Cart", "Giohang", "MonAn", new { UserName = ViewBag.UserName }, new { id = "signup" })

    @Html.ActionLink("Log Out", "LogOff", "Account", null, new { id = "login" })

    if (@User.Identity.GetUserName() == "admin")
    {
        // @Html.Label("|", new { id = "temp1" })
        @Html.ActionLink("admin", "Admin", "MonAn", null, new { id = "login" })
        //<span id="login">(@ViewBag.UserName)</span>
    }
    else
    {

        @Html.Label("|", new { id = "temp1" })
        @Html.ActionLink(User.Identity.GetUserName(), "TaiKhoan", "MonAn", null, new { id = "login" })
    }


}
        </div>
    </div>
    <div class="row" id="main_menu">
        <div class="col-xs-4" id="menu_home">
            <img id="img_home" src="~/img/icon_home.png" />@Html.ActionLink("Home", "Index")
        </div>

        <div class="col-xs-4" id="menu_angi">
            <img id="img_angi" src="~/img/icon_food.png" />@Html.ActionLink("Ăn gì", "ListTheoAnGi")
        </div>
        <div class="col-xs-4" id="menu_odau">
            <img id="img_odau" src="~/img/icon_diferent.png" />@Html.ActionLink("Ở đâu", "ListTheoODau")
        </div>
        <div class="col-xs-4" id="menu_chiase">
            <img id="img_chiase" src="~/img/icon_love.png" />Chia sẻ
        </div>

        <div class="col-xs-4" id="menu_about">
            <img id="img_about" src="~/img/icon_edit.PNG" />@Html.ActionLink("About", "About")
        </div>
    </div>
    <div class="row" id="sub_menu">
        <marquee direction="right" scrolldelay="5" scrollamount="5" onmouseover="this.stop()" onmouseout="this.start()">
            <span class="text_run">Click and enjoy now!!!</span>
            <img class="sub_menu_img" src="~/img/Slider_img1.png" />
            <img class="sub_menu_img" src="~/img/Slider_img2.png" />
            <img class="sub_menu_img" src="~/img/Slider_img3.png" />
            <img class="sub_menu_img" src="~/img/Slider_img4.png" />
            <img class="sub_menu_img" src="~/img/Slider_img5.png" />
            <img class="sub_menu_img" src="~/img/Slider_img6.png" />
            <span class="text_run">Click and enjoy now!!!</span>
        </marquee>
    </div>
    <div class="row" id="backgroundSingup">
        @using (Html.BeginForm("KetQuaDangKy", "DangKy", FormMethod.Post))
        {
            <div class="row">
                <div class="col-md-12">
                    @Html.Label("ĐĂNG KÝ TÀI KHOẢN", new { @id = "tittle" })
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    @Html.Label("Thông tin tài khoản", new { @class = "sub_tittle" })
                </div>
            </div>

            <div class="row" id="row1_1">
                <div class="col-xs-4" id="part1_1">
                    @Html.Label("Tên đăng nhập", new { @class = "name_tittle" })
                </div>
                <div class="col-xs-4" id="part2_1">
                    @Html.TextBoxFor(m => m.TenTaiKhoan, "", new { @class = "textbox" })
                    @Html.ValidationMessageFor(m => m.TenTaiKhoan)
                </div>
            </div>

            <div class="row" id="row2_1">
                <div class="col-xs-4" id="part1_2">
                    @Html.Label("Mật khẩu", new { @class = "name_tittle" })
                </div>
                <div class="col-xs-4" id="part2_2">
                    @Html.PasswordFor(m => m.MatKhau, new { @class = "textbox" })
                    @Html.ValidationMessageFor(m => m.MatKhau)
                </div>
            </div>

            <div class="row" id="row3_1">
                <div class="col-xs-4" id="part1_3">
                    @Html.Label("Nhập lại mật khẩu", new { @class = "name_tittle" })
                </div>
                <div class="col-xs-4" id="part2_3">
                    @Html.PasswordFor(m => m.NhapLaiMatKhau, new { @class = "textbox" })
                    @Html.ValidationMessageFor(m => m.NhapLaiMatKhau)
                </div>
            </div>

            <div class="row" id="row4_1">
                <div class="col-xs-4" id="part1_4">
                    @Html.Label("Email", new { @class = "name_tittle" })
                </div>
                <div class="col-xs-4" id="part2_4">
                    @Html.TextBoxFor(m => m.Email, new { @class = "textbox" })
                    @Html.ValidationMessageFor(m => m.Email)
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    @Html.Label("Thông tin cá nhân", new { @class = "sub_tittle" })
                </div>
            </div>

            <div class="row" id="row1_2">
                <div class="col-xs-4" id="part1_1">
                    @Html.Label("Giới tính", new { @class = "name_tittle" })
                </div>
                <div class="col-xs-4" id="part2_1">
                    @Html.DropDownList("cbGioiTinh", new List<SelectListItem>{
                new SelectListItem {Text = "Nam", Value = "nam", Selected = true},
                new SelectListItem {Text = "Nữ", Value = "nu"}
            }, new { @class = "textbox" })

                </div>
            </div>

            <div class="row" id="row2_1">
                <div class="col-xs-4" id="part1_2">
                    @Html.Label("Ngày tháng năm sinh", new { @class = "name_tittle" })
                </div>
                <div class="col-xs-4" id="part2_2">
                    <div class="textbox">
                        <input type="text" id="datepicker" name="datepicker" value="01/01/2014">
                    </div>
                </div>
            </div>

            <div class="row" id="row3_1">
                <div class="col-xs-4" id="part1_3">
                    @Html.Label("Nơi ở hiện tại", new { @class = "name_tittle" })
                </div>
                <div class="col-xs-4" id="part2_3">
                    @Html.DropDownList("cbNoiO", new List<SelectListItem>{
                new SelectListItem {Text = "Hồ Chí Minh", Value = "hcm", Selected=true},
                new SelectListItem {Text = "Hà Nội", Value = "hn"},
                new SelectListItem {Text = "Huế", Value = "hue"},
            }, new { @class = "textbox" })
                </div>
            </div>

            <div class="row" id="row4_1">
                <div class="col-xs-4" id="part1_4">
                    @Html.Label("Điện thoại liên lạc", new { @class = "name_tittle" })
                </div>
                <div class="col-xs-4" id="part2_4">
                    @Html.TextBoxFor(m => m.DienThoai, "", new { @class = "textbox" })
                    @Html.ValidationMessageFor(m => m.DienThoai)
                </div>
            </div>
            <input class="name_tittle" type="submit" value="Đăng kí" />

        }
    </div>
    
    
    <div class="row" id="bottom_main">
        <div class="col-xs-12" id="content_bottom">
            Đồ án môn học Phát triển ứng dụng web
            <br />
            Sinh viên thực hiện:
            <br />
            Trương Ngọc Thịnh - Phạm Hữu Nhân
        </div>
    </div>
</div> <!-- /container -->
<script src="~/Scripts/jquery-ui-1.10.4.custom.min.js"></script>
<link href="~/Content/jquery-ui-1.10.4.custom.min.css" rel="stylesheet" />

<script src="~/Scripts/jquery-1.11.0.min.js"></script>
<script>
    id = 0;
    $('#menu_angi').hover(function () {
        id = 1;
        $('#sub_menu').html("<div class='col-xs-4' id='sub_menu_heo'> <img class='img_animal' src='../../img/icon_heo.jpg' /> Heo </div><div class='col-xs-4' id='sub_menu_bo'><img class='img_animal' src='../../img/icon_bo.jpg' />Bò</div><div class='col-xs-4' id='sub_menu_ga'><img class='img_animal' src='../../img/icon_ga.jpg' />Gà</div><div class='col-xs-4' id='sub_menu_haisan'><img class='img_animal' src='../../img/icon_haisan.jpg' />Hải sản</div><div class='col-xs-4' id='sub_menu_khac'><img class='img_animal' src='../../img/icon_khac_angi.jpg' />Khác</div>");
    });

    $('#menu_odau').hover(function () {
        id = 1;
        $('#sub_menu').html("<div class='col-xs-4' id='sub_menu_tphcm'><img  src='../../img/icon_tphcm.png' />Món ăn miền nam</div><div class='col-xs-4' id='sub_menu_hanoi'><img src='../../img/icon_hanoi.png' />Món ăn miền bắc</div><div class='col-xs-4' id='sub_menu_hue'><img src='../../img/icon_hue.png' />Món ăn miền trung</div>");
    });
    $('#menu_home').hover(function () {
        if (id != 0) {
            id = 0;
            $('#sub_menu').html("<marquee direction='right' scrolldelay='5' scrollamount='5' onmouseover='this.stop()' onmouseout='this.start()'><span class='text_run'>Click and enjoy now!!!</span><img class='sub_menu_img' src='../../img/Slider_img1.png' /><img class='sub_menu_img' src='../../img/Slider_img2.png' /><img class='sub_menu_img' src='../../img/Slider_img3.png' /><img class='sub_menu_img' src='../../img/Slider_img4.png' /><img class='sub_menu_img' src='../../img/Slider_img5.png' /><img class='sub_menu_img' src='../../img/Slider_img6.png' /><span class='text_run'>Click and enjoy now!!!</span></marquee>");
        }
    });
    $('#menu_chiase').hover(function () {
        if (id != 0) {
            id = 0;
            $('#sub_menu').html("<marquee direction='right' scrolldelay='5' scrollamount='5' onmouseover='this.stop()' onmouseout='this.start()'><span class='text_run'>Click and enjoy now!!!</span><img class='sub_menu_img' src='../../img/Slider_img1.png' /><img class='sub_menu_img' src='../../img/Slider_img2.png' /><img class='sub_menu_img' src='../../img/Slider_img3.png' /><img class='sub_menu_img' src='../../img/Slider_img4.png' /><img class='sub_menu_img' src='../../img/Slider_img5.png' /><img class='sub_menu_img' src='../../img/Slider_img6.png' /><span class='text_run'>Click and enjoy now!!!</span></marquee>");
        }
    });
    $('#menu_about').hover(function () {
        if (id != 0) {
            id = 0;
            $('#sub_menu').html("<marquee direction='right' scrolldelay='5' scrollamount='5' onmouseover='this.stop()' onmouseout='this.start()'><span class='text_run'>Click and enjoy now!!!</span><img class='sub_menu_img' src='../../img/Slider_img1.png' /><img class='sub_menu_img' src='../../img/Slider_img2.png' /><img class='sub_menu_img' src='../../img/Slider_img3.png' /><img class='sub_menu_img' src='../../img/Slider_img4.png' /><img class='sub_menu_img' src='../../img/Slider_img5.png' /><img class='sub_menu_img' src='../../img/Slider_img6.png' /><span class='text_run'>Click and enjoy now!!!</span></marquee>");
        }
    });

    $('#login').click(function () {
        $('#login_signup').html("Tài khoản<input id='taikhoan' type='text'><a class='btnSignUp'href='SignUp.html'><input class='btnSignUp' type='button' value='Sign Up'></a><br />Mật khẩu<input id='matkhau' type='password'><input id='btnLogin' type='button' value='Login'>");
    });

</script>
<link href="~/Content/login.css" rel="stylesheet" />
<link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

<script>
    $(function () {
        $("#datepicker").datepicker();
    });

</script>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript">
</script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>